name: Update llms.txt

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering
  repository_dispatch: # Allow external triggers
    types: [update-llms]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-llms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create venv and install dependencies
        run: |
          uv venv
          . .venv/bin/activate
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            uv pip install git+https://github.com/ngmisl/llmstxt.git
          else
            uv pip install -e .
          fi

      - name: Clone target repository
        if: github.event_name == 'repository_dispatch'
        run: |
          git clone ${{ github.event.client_payload.repository }} target_repo
          cd target_repo
          python -c "from llmstxt import generate_llms_txt; generate_llms_txt()"

      - name: Generate llms.txt for current repository
        if: github.event_name != 'repository_dispatch'
        run: |
          . .venv/bin/activate
          python -c "from llmstxt import generate_llms_txt; generate_llms_txt()"

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet llms.txt; then
            echo "No changes to llms.txt"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in llms.txt"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update llms.txt"
          title: "chore: update llms.txt"
          body: |
            This PR updates the llms.txt file with the latest code compression.

            Changes were automatically generated by [llmstxt](https://github.com/ngmisl/llmstxt).
          branch: update-llms
          delete-branch: true
